/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,jsx,ts,tsx}'],
  theme: {
    extend: {
      colors: {
        'surface-container-highest': '#e0e3e1',
        'on-surface-variant': '#3d4a3f',
        'ai-tint': '#E6F6EE',
        'on-secondary-fixed-variant': '#244f39',
        background: '#f7faf8',
        'on-surface': '#181c1b',
        'on-tertiary-fixed-variant': '#643f00',
        'text-deep': '#282B3E',
        'surface-container-high': '#e6e9e7',
        'surface-tint': '#006d37',
        'status-red': '#C14A36',
        'secondary-fixed': '#beedcf',
        'on-tertiary': '#ffffff',
        'inverse-surface': '#2d3130',
        'outline-variant': '#bccabb',
        'primary-fixed': '#78fca2',
        outline: '#6d7b6e',
        'secondary-container': '#b9e8ca',
        'surface-dim': '#d7dbd9',
        'on-primary-container': '#003216',
        'on-primary-fixed': '#00210d',
        'surface-container-low': '#f1f4f2',
        'on-secondary-fixed': '#002112',
        'tertiary-fixed': '#ffddb6',
        tertiary: '#845400',
        'surface-container-lowest': '#ffffff',
        'on-secondary': '#ffffff',
        'surface-bright': '#f7faf8',
        'tertiary-fixed-dim': '#ffb959',
        'muted-blue': '#4A90E2',
        'secondary-fixed-dim': '#a3d1b4',
        'surface-variant': '#e0e3e1',
        'tertiary-container': '#c7830f',
        'primary-fixed-dim': '#5adf89',
        primary: '#006d37',
        'on-primary': '#ffffff',
        'primary-container': '#00a758',
        'on-error': '#ffffff',
        'on-tertiary-container': '#3e2500',
        secondary: '#3c674f',
        'on-primary-fixed-variant': '#005228',
        'inverse-primary': '#5adf89',
        error: '#ba1a1a',
        'surface-white': '#FFFFFF',
        surface: '#f7faf8',
        'error-container': '#ffdad6',
        'on-secondary-container': '#3f6a52',
        'inverse-on-surface': '#eef1ef',
        'on-error-container': '#93000a',
        'surface-container': '#ebefed',
        'on-tertiary-fixed': '#2a1800',
        'on-background': '#181c1b',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        'margin-mobile': '16px',
        gutter: '24px',
        'margin-desktop': '32px',
        'container-max': '1440px',
        unit: '4px',
      },
      fontFamily: {
        'kpi-value': ['Plus Jakarta Sans'],
        'headline-md': ['Plus Jakarta Sans'],
        'headline-lg-mobile': ['Plus Jakarta Sans'],
        'body-md': ['Plus Jakarta Sans'],
        'label-sm': ['Plus Jakarta Sans'],
        'headline-lg': ['Plus Jakarta Sans'],
        'label-md': ['Plus Jakarta Sans'],
        'display-lg': ['Plus Jakarta Sans'],
        'body-lg': ['Plus Jakarta Sans'],
      },
      fontSize: {
        'kpi-value': ['28px', { lineHeight: '34px', fontWeight: '800' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'headline-lg-mobile': ['24px', { lineHeight: '32px', fontWeight: '700' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'label-sm': ['12px', { lineHeight: '16px', letterSpacing: '0.02em', fontWeight: '500' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '700' }],
        'label-md': ['14px', { lineHeight: '20px', letterSpacing: '0.01em', fontWeight: '600' }],
        'display-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '800' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
      },
    },
  },
  plugins: [],
}
