import { useState } from 'react';
import { usePrototype } from '../context/PrototypeContext';

export default function ContentStudio() {
  const [type, setType] = useState('Email'); const [generated, setGenerated] = useState(false); const [loading, setLoading] = useState(false); const [submitted, setSubmitted] = useState(false);
  const { role, approvals, submitForApproval } = usePrototype(); const submitter = role === 'Advisor' ? 'James Peterson' : 'Sarah Jenkins';
  const generate = () => { setGenerated(false); setLoading(true); window.setTimeout(() => { setLoading(false); setGenerated(true); }, 900); };
  const submit = () => { submitForApproval({ title: `${type}: Retirement planning review`, preview: 'Invite Jean-Pierre to review retirement and estate-planning needs.' }); setSubmitted(true); };
  return <section className="p-4 md:p-8 space-y-6 bg-surface-gray min-h-full"><div><p className="text-primary font-semibold text-sm">Prospect + Sell</p><h2 className="text-3xl font-bold">Content Studio</h2><p className="text-on-surface-variant mt-1">Draft compliant customer communications with mock AI assistance.</p></div><div className="grid lg:grid-cols-2 gap-6"><div className="bg-white rounded-xl border border-outline-variant shadow-sm p-6 space-y-5"><h3 className="text-xl font-bold">Create a communication</h3><label className="block text-sm font-semibold">Content type<select value={type} onChange={(e) => setType(e.target.value)} className="mt-2 w-full rounded-lg border border-outline-variant p-3"><option>Email</option><option>WhatsApp</option><option>Social post</option></select></label><label className="block text-sm font-semibold">Customer<input defaultValue="Jean-Pierre Tremblay" className="mt-2 w-full rounded-lg border border-outline-variant p-3" /></label><label className="block text-sm font-semibold">Objective<textarea defaultValue="Invite the customer to review retirement and estate-planning needs." className="mt-2 w-full rounded-lg border border-outline-variant p-3 min-h-28" /></label><button onClick={generate} disabled={loading} className="bg-primary text-white px-5 py-3 rounded-lg font-semibold disabled:opacity-60">{loading ? 'AI is drafting…' : `Generate ${type} draft`}</button></div><div className="bg-white rounded-xl border border-outline-variant shadow-sm p-6"><h3 className="text-xl font-bold mb-4">Draft and compliance check</h3>{!generated ? <p className="text-on-surface-variant">{loading ? 'AI is thinking and checking compliant language…' : 'Choose a content type and generate a draft to begin.'}</p> : <><div className="rounded-lg bg-surface-container-low p-4 text-sm leading-6"><strong>Subject: Your retirement planning review</strong><br /><br />Hello Jean-Pierre, I’d welcome the opportunity to review your retirement and estate-planning goals using options suited to your needs and risk profile.</div><div className="mt-5 text-sm text-primary">✓ Approved product language<br />✓ No performance guarantees<br />✓ Customer consent recorded</div><button onClick={submit} disabled={submitted} className="mt-5 border border-primary text-primary px-4 py-2 rounded-lg font-semibold">{submitted ? 'Submitted' : 'Submit for Approval'}</button>{submitted && <p className="mt-3 text-primary font-semibold">Submitted to Compliance as Pending.</p>}<div className="mt-6 border-t pt-4"><p className="font-semibold text-sm mb-2">My submission history</p>{approvals.filter((item) => item.submitter === submitter).map((item) => <div key={item.id} className="text-sm flex justify-between py-1"><span>{item.title}</span><span className="px-2 rounded-full bg-surface-container text-on-surface-variant">{item.status}</span></div>)}</div></>}</div></div></section>;
}
