import { usePrototype } from '../context/PrototypeContext';

export default function MyDay() {
  const { tasks, completeTask } = usePrototype();
  const completed = tasks.filter((task) => task.done);
  const points = completed.reduce((sum, task) => sum + task.points, 120);
  return <section className="p-8 bg-surface-gray min-h-full space-y-6">
    <div className="flex flex-col lg:flex-row lg:justify-between lg:items-end gap-3"><div><p className="text-primary font-semibold text-sm">Activate · Sell · Service</p><h2 className="text-3xl font-bold">My Day</h2><p className="text-on-surface-variant mt-1">A mock priority queue for Advisor James Wilson.</p></div><div className="rounded-xl bg-primary text-white px-5 py-3"><span className="text-sm opacity-80">Current streak</span><p className="font-bold text-xl">6 days</p></div></div>
    <div className="grid md:grid-cols-3 gap-5"><article className="bg-white rounded-xl border border-outline-variant shadow-sm p-5"><p className="text-sm text-on-surface-variant">Tasks complete</p><p className="text-3xl font-bold mt-2">{completed.length}/{tasks.length}</p></article><article className="bg-white rounded-xl border border-outline-variant shadow-sm p-5"><p className="text-sm text-on-surface-variant">Rewards points</p><p className="text-3xl font-bold mt-2 text-primary">{points}</p></article><article className="bg-white rounded-xl border border-outline-variant shadow-sm p-5"><p className="text-sm text-on-surface-variant">Next meeting</p><p className="text-xl font-bold mt-2">11:00 AM</p><p className="text-sm text-on-surface-variant">Tremblay renewal review</p></article></div>
    <div className="grid xl:grid-cols-[1.6fr_1fr] gap-6"><div className="bg-white rounded-xl border border-outline-variant shadow-sm overflow-hidden"><div className="p-6 border-b border-outline-variant flex justify-between"><div><h3 className="text-xl font-bold">AI-ranked tasks</h3><p className="text-sm text-on-surface-variant">Prioritised by mock customer value and urgency.</p></div><span className="text-primary font-semibold text-sm">Next best actions</span></div><div className="divide-y divide-outline-variant">{tasks.map((task) => <div key={task.id} className="p-5 flex gap-4 items-center"><button disabled={task.done} onClick={() => completeTask(task.id)} className={`w-6 h-6 rounded-full border-2 flex-none ${task.done ? 'bg-primary border-primary text-white' : 'border-primary'}`}>{task.done && '✓'}</button><div className="flex-1"><p className={`font-semibold ${task.done ? 'line-through text-on-surface-variant' : ''}`}>{task.title}</p><p className="text-sm text-on-surface-variant mt-1">{task.priority} priority · {task.points} points</p></div>{!task.done && <button onClick={() => completeTask(task.id)} className="text-primary font-semibold text-sm">Complete</button>}</div>)}</div></div>
      <aside className="space-y-5"><div className="bg-white rounded-xl border border-outline-variant shadow-sm p-6"><h3 className="text-xl font-bold">Leaderboard</h3><ol className="mt-4 space-y-4 text-sm"><li className="flex justify-between"><span>1. Priya Kapoor</span><b>460</b></li><li className="flex justify-between"><span>2. James Wilson</span><b className="text-primary">{points}</b></li><li className="flex justify-between"><span>3. Alex Chen</span><b>260</b></li></ol></div><div className="bg-primary/10 border border-primary/20 rounded-xl p-6"><h3 className="font-bold">AI focus</h3><p className="text-sm mt-2">Completing the Tremblay follow-up first preserves a high-value renewal opportunity.</p></div></aside></div>
  </section>;
}
